### ISSUE TITLE
design for menu popup for boards and communities

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-design#1]
@PonteIneptique @TDBuck and Rafael (gh address??) The Boards and Communities buttons in the main left nav menu bar -- in the current system these produce menus which list the available boards and communities.  I think the design needs to account for that with sub-nav menus.

**Comment by PonteIneptique** [comment]
It does account. I just did not implement for now

**Comment by balmas** [comment]
awesome thanks.

**Comment by PonteIneptique** [comment]
Rafael is @Heargrove since tonight :)

**Comment by PonteIneptique** [comment]
@Heargrove, @balmas and @TDBuck : feel free to review the dropdown :) I test only in firefox 100% of the time, so safari and chrome testing are welcome

**Comment by balmas** [comment]
resolved.
