### ISSUE TITLE
design guidance:  nav on treebank sentence list

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-design#10]
It's possible for a treebank sentence list (the Edit view of a treebank) to have multiple pages (we currently only show up to 50 sentences at at time).  The new design doesn't take this into account.   Suggestions welcome.

@Heargrove

**Comment by Heargrove** [comment]
Hello @balmas Could you upload a screenshot here ?

**Comment by balmas** [comment]
![screenshot from 2016-11-02 16 42 19](https://cloud.githubusercontent.com/assets/644870/19946684/5923b1e6-a11b-11e6-81cf-5173d69ba7db.png)
![Uploading Screenshot from 2016-11-02 16:41:20.png…]()

**Comment by balmas** [comment]
![screenshot from 2016-11-02 16 41 20](https://cloud.githubusercontent.com/assets/644870/19946701/710d1cc0-a11b-11e6-8bef-e671d8455530.png)

**Comment by balmas** [comment]
similarly, need nav on boards dashboard when we have > displayable number of publications to vote on. 

(See Next/Prev 50 links on this screenshot) 

![screenshot from 2016-11-23 10 12 22](https://cloud.githubusercontent.com/assets/644870/20567078/69bf526c-b165-11e6-9163-7c98b2a5eb1c.png)

**Comment by Heargrove** [comment]
Hello,

Tell me if it's sounds ok to you.
![arrows_1](https://cloud.githubusercontent.com/assets/20712913/21430479/a16c2842-c863-11e6-8a4a-81b0cff3995d.png)
![arrows_2](https://cloud.githubusercontent.com/assets/20712913/21430478/a16b665a-c863-11e6-9cfc-eb2ff7a976dc.png)
![arrows_3](https://cloud.githubusercontent.com/assets/20712913/21430480/a16c245a-c863-11e6-86b9-53b8ae8ba2da.png)

**Comment by balmas** [comment]
those look nice to me.  Do you hava a png for the arrows, or are we going to do them with pure CSS?

**Comment by Heargrove** [comment]
What's the best for you ?

**Comment by balmas** [comment]
well if we can use font-awesome css icons it's good, that's what thibault was thinking these were

**Comment by Heargrove** [comment]
Hello,

I just need to know if we're ok here.

Bests

**Comment by balmas** [comment]
@Heargrove are the < > icons font awesome icons? if so, just tell me which ones and we are good. Thanks.

**Comment by PonteIneptique** [comment]
http://fontawesome.io/icon/chevron-left/ and
http://fontawesome.io/icon/chevron-right/ :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by balmas** [comment]
ok thanks. closing.
