### ISSUE TITLE
publication overview -submitted

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-design#14]
when a publication has been submitted, we have fewer options. need to revisit design of this page.

Also, some buttons, such as "Withdraw from Editorial Review" exceed the size currently set as the max. Shall I just extend the size on a per-button basis in that case?
![screenshot from 2016-10-07 15 59 08](https://cloud.githubusercontent.com/assets/644870/19203788/43ed0d1e-8ca7-11e6-846a-0259c9d0b98d.png)

**Comment by PonteIneptique** [comment]
I think in this case you should use the horizontal menu of  http://perseids-project.github.io/perseids-design/design/treebank.html

**Comment by balmas** [comment]
that's a good suggestion

**Comment by balmas** [comment]
implemented.
