### ISSUE TITLE
Decide main categories and their icon

### ISSUE THREAD

**Issue by PonteIneptique** [perseids-project/perseids-design#15]
@balmas Could you give me the main categories Perseids should have ? And potentially choose an icon on http://fontawesome.io/icons/ ?

**Comment by balmas** [comment]
Publication 

Treebank (icon suggestion: tree??)

Translation Alignment (icon suggestion: align justify??)

XML Text Transcription (icon suggestion: file text?)

XML Text Translation (icon suggestion: file text?)

XML Text Passage (icon suggestion: file text?)

Commentary Annotation  (icon suggestion: comments bubbles)

Text Annotation (icon suggestion: sticky note)
(We can use the same symbol for RDF/XML and JSON-LD I think)

Syriaca Place Gazetteer (we should try to use a Syriaca Icon)

**Comment by balmas** [comment]
back to you @heargrove and @PonteIneptique

**Comment by balmas** [comment]
@bitfield raises the point that using the same icon with different colors (as we are doing with the text and translation) is an accessibility issue.  is there a variation on file text that we could use for translation?

**Comment by balmas** [comment]
I think the best solution is to just have a single icon/color for all text (whether translation, transcription or passage). the difference isn't significant enough to warrant confusion introduced by mutiple icons or colors.

**Comment by balmas** [comment]
this is done.
