### ISSUE TITLE
design guidance for headers

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-design#17]
we need the guidelines to include guidance on how and were to apply headers

e.g. see attached screenshot.  The "Preview" is a label right now and looks a little weird in the current design.
![labels](https://cloud.githubusercontent.com/assets/644870/20445342/b671d902-ada2-11e6-99e9-5d8678ff6b99.png)

**Comment by Heargrove** [comment]
Hello,

If i get it right, "Preview" is supposed to be a "Title" not a header. The title size and font are in the guidelines.

Tell me if I didn't get it right.

![perseids_title](https://user-images.githubusercontent.com/20712913/27498671-7ac17ee4-5860-11e7-9bbd-9a3f5541604c.jpg)

**Comment by balmas** [comment]
ok that's fine. thanks.
