### ISSUE TITLE
need to adjust login page design

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-design#4]
@Heargrove , @TDBuck , @PonteIneptique 

I am going to need to adjust the login page design a bit.  Due to our use of a 3rd party provider, we don't have control over the display of the social identity widget, and for the Institutional Login, the logos come from the providers.

What i'd like to do is move those elements back into the main page, and maybe move the "read more" and "sample publications" links into the sidebar instead.

What do you think?

**Comment by PonteIneptique** [comment]
Can you give us again the third party provider link ?

**Comment by balmas** [comment]
I'm happy with the current login page design so marking this done.
