### ISSUE TITLE
need design guidance for flash notices

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-design#5]
I  need some guidance on where the app flash notices should display in the new design.  I've attached screenshots of some currently notices
We have the following categories of this right now:

error
warning
info

![screenshot from 2016-09-28 16 58 18](https://cloud.githubusercontent.com/assets/644870/18932055/d052d566-859c-11e6-945e-9cdc14ac51a9.png)
![screenshot from 2016-09-28 16 57 32](https://cloud.githubusercontent.com/assets/644870/18932056/d05bd63e-859c-11e6-9a00-cd22aa8f38a5.png)

**Comment by balmas** [comment]
want to assign this @Heargrove but I need to add him to the repo first..

**Comment by balmas** [comment]
We're close on this, but I need design guidance on colors and icons. There are 4 distinct types.  At the moment I'm using the same design for each but we need to differentiate.  Here's an example of some:
Error
![error](https://cloud.githubusercontent.com/assets/644870/21233100/f58cbb10-c2bb-11e6-8006-44e893d3fcb8.png)

Warning
(no screenshot, but it lies between error and info in terms of severity)

Info
![info](https://cloud.githubusercontent.com/assets/644870/21233115/0854f3d4-c2bc-11e6-83a2-4f1e11b56d43.png)

Hints
![hints](https://cloud.githubusercontent.com/assets/644870/21233122/0e5cc3e2-c2bc-11e6-9c24-a2258166450a.png)

**Comment by balmas** [comment]
I see that we had colors in there for success and danger, so I used those for notice and error:
![error](https://cloud.githubusercontent.com/assets/644870/21321073/46c2edce-c5e1-11e6-8927-be8d45446607.png)
![success](https://cloud.githubusercontent.com/assets/644870/21321074/46d78626-c5e1-11e6-9a96-92ee3dbe3dc6.png)

Need still for hints and warning

**Comment by Heargrove** [comment]
![warning_hint](https://cloud.githubusercontent.com/assets/20712913/21430568/06f74b9c-c864-11e6-9673-c47970f032e5.png)
Let me now if it's ok.

It's probably too much saturated no ?

**Comment by balmas** [comment]
looks great to me. Thank you!
