### ISSUE TITLE
Link Design

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-design#6]
for @Heargrove
- [ ] what color should links be? the same as the color on a simple button? and what colors for hover, visited, etc?

**Comment by balmas** [comment]
Design currently has black and no change in color for hover, visited, etc. Not sure if this was intentional? I personally think links should be colored.

**Comment by balmas** [comment]
darker version of the primary color

**Comment by Heargrove** [comment]
Hello, 
Here is a screenshot.

![hyperlink_color](https://cloud.githubusercontent.com/assets/20712913/21430526/d87ba312-c863-11e6-93af-f41f97a99aaf.png)

**Comment by balmas** [comment]
ok!
