### ISSUE TITLE
nav on edit bar

### ISSUE THREAD

**Issue by balmas** [perseids-project/perseids-design#8]
@Heargrove @TDBuck 

The current edit page has little navigation arrows that allow to navigate between items in your workspace.  I have no idea if anyone uses these, or if we care, but they aren't in the current design.  Should we keep this functionality, and if so, how should it be represented in the new design?

See screenshot from current interface. I'm talking about the `<`and `>` buttons on the right side of the gray bar.
![screenshot from 2016-10-03 14 47 24](https://cloud.githubusercontent.com/assets/644870/19049422/66add4f0-8978-11e6-8a6e-6d0b12267f2d.png)

**Comment by TDBuck** [comment]
I remember using them at some point years ago. But if they have been broken for a while an no one has complained, then we probably don't need to have them.

**Comment by balmas** [comment]
ah, they aren't broken now (but my text above was a bit, which maybe led you to believe they were -- I meant 'arrows' not 'errors', corrected now)

**Comment by PonteIneptique** [comment]
Relates to http://perseids-project.github.io/perseids-design/design/pubOverview.html
Still want that ?

**Comment by balmas** [comment]
I can take or leave the navigation arrows between publications. I don't know if anyone uses them.

I do need navigation arrows on the treebank and alignment sentence lists though.

**Comment by Heargrove** [comment]
@balmas @PonteIneptique I'll make them. Don't worry

**Comment by balmas** [comment]
making an executive decision to drop this navigation.
